// <auto-generated />
namespace CMDLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedRentedDate_ReturnTermColumnsToBooksTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRentedDate_ReturnTermColumnsToBooksTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281150454_AddedRentedDate_ReturnTermColumnsToBooksTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
